2020-01-26 00:35:50,745 INFO: Microblog startup [in C:\Users\Raynolds\PycharmProjects\Blog\app\__init__.py:77]
2020-01-26 00:38:30,937 INFO: Microblog startup [in C:\Users\Raynolds\PycharmProjects\Blog\app\__init__.py:77]
2020-01-26 00:39:35,995 INFO: Microblog startup [in C:\Users\Raynolds\PycharmProjects\Blog\app\__init__.py:77]
2020-01-26 00:39:47,450 INFO: Microblog startup [in C:\Users\Raynolds\PycharmProjects\Blog\app\__init__.py:77]
2020-01-26 00:39:55,089 INFO: Microblog startup [in C:\Users\Raynolds\PycharmProjects\Blog\app\__init__.py:77]
2020-01-26 00:52:02,982 INFO: Microblog startup [in C:\Users\Raynolds\PycharmProjects\Blog\app\__init__.py:77]
2020-01-26 01:27:54,935 INFO: Microblog startup [in /mnt/c/Users/Raynolds/PycharmProjects/Blog/app/__init__.py:77]
2020-01-26 01:28:05,500 INFO: Microblog startup [in /mnt/c/Users/Raynolds/PycharmProjects/Blog/app/__init__.py:77]
2020-01-26 01:35:42,823 INFO: Microblog startup [in /mnt/c/Users/Raynolds/PycharmProjects/Blog/app/__init__.py:81]
2020-01-26 01:37:23,794 INFO: Microblog startup [in /mnt/c/Users/Raynolds/PycharmProjects/Blog/app/__init__.py:81]
2020-01-26 01:37:44,561 INFO: Microblog startup [in /mnt/c/Users/Raynolds/PycharmProjects/Blog/app/__init__.py:81]
2020-01-26 01:41:02,751 INFO: Microblog startup [in C:\Users\Raynolds\PycharmProjects\Blog\app\__init__.py:81]
2020-01-26 01:45:30,933 INFO: Microblog startup [in C:\Users\Raynolds\PycharmProjects\Blog\app\__init__.py:81]
2020-01-26 01:49:23,265 INFO: Microblog startup [in C:\Users\Raynolds\PycharmProjects\Blog\app\__init__.py:81]
2020-01-26 01:49:36,975 ERROR: Exception on /auth/reset_password_request [POST] [in C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Raynolds\PycharmProjects\Blog\app\auth\routes.py", line 61, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\Raynolds\PycharmProjects\Blog\app\auth\email.py", line 7, in send_password_reset_email
    token = user.get_reset_password_token()
  File "C:\Users\Raynolds\PycharmProjects\Blog\app\models.py", line 80, in get_reset_password_token
    return jwt.encode(
AttributeError: module 'jwt' has no attribute 'encode'
2020-01-26 01:52:56,714 INFO: Microblog startup [in C:\Users\Raynolds\PycharmProjects\Blog\app\__init__.py:81]
2020-01-26 01:53:08,541 ERROR: Exception on /auth/reset_password_request [POST] [in C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Raynolds\PycharmProjects\Blog\app\auth\routes.py", line 61, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\Raynolds\PycharmProjects\Blog\app\auth\email.py", line 9, in send_password_reset_email
    sender=current_app.config['ADMINS'][0],
IndexError: list index out of range
2020-01-26 01:54:14,524 INFO: Microblog startup [in C:\Users\Raynolds\PycharmProjects\Blog\app\__init__.py:81]
2020-01-26 01:54:24,093 ERROR: Exception on /auth/reset_password_request [POST] [in C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Raynolds\PycharmProjects\Blog\app\auth\routes.py", line 61, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\Raynolds\PycharmProjects\Blog\app\auth\email.py", line 12, in send_password_reset_email
    user=user, token=token),
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\templating.py", line 140, in render_template
    ctx.app,
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Raynolds\PycharmProjects\Blog\app\templates\email\reset_password.txt", line 5, in top-level template code
    {{ url_for('reset_password', token=token, _external=True) }}
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\flask\helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "C:\Users\Raynolds\PycharmProjects\Blog\lib\site-packages\werkzeug\routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'reset_password' with values ['token']. Did you mean 'auth.reset_password' instead?
2020-01-26 01:56:13,654 INFO: Microblog startup [in C:\Users\Raynolds\PycharmProjects\Blog\app\__init__.py:81]
2020-01-26 01:58:25,184 INFO: Microblog startup [in C:\Users\Raynolds\PycharmProjects\Blog\app\__init__.py:81]
2020-01-26 02:00:36,045 INFO: Microblog startup [in C:\Users\Raynolds\PycharmProjects\Blog\app\__init__.py:81]
2020-01-26 02:03:06,288 INFO: Microblog startup [in C:\Users\Raynolds\PycharmProjects\Blog\app\__init__.py:81]
2020-01-26 02:04:57,984 INFO: Microblog startup [in C:\Users\Raynolds\PycharmProjects\Blog\app\__init__.py:81]
2020-01-26 02:22:18,115 INFO: Microblog startup [in C:\Users\Raynolds\PycharmProjects\Blog\app\__init__.py:81]
2020-01-26 02:24:30,403 INFO: Microblog startup [in C:\Users\Raynolds\PycharmProjects\Blog\app\__init__.py:81]
2020-01-26 02:26:24,012 INFO: Microblog startup [in C:\Users\Raynolds\PycharmProjects\Blog\app\__init__.py:81]
2020-01-26 02:28:44,551 INFO: Microblog startup [in C:\Users\Raynolds\PycharmProjects\Blog\app\__init__.py:81]
2020-01-26 02:29:25,348 INFO: Microblog startup [in ./app/__init__.py:81]
2020-01-26 02:35:12,362 INFO: Microblog startup [in C:\Users\Raynolds\PycharmProjects\Blog\app\__init__.py:81]
2020-01-26 02:35:20,265 INFO: Microblog startup [in ./app/__init__.py:81]
2020-01-26 02:43:22,750 INFO: Microblog startup [in ./app/__init__.py:81]
2020-01-26 02:58:20,921 INFO: Microblog startup [in C:\Users\Raynolds\PycharmProjects\Blog\app\__init__.py:84]
2020-01-26 03:01:31,982 INFO: Microblog startup [in C:\Users\Raynolds\PycharmProjects\Blog\app\__init__.py:84]
2020-01-26 03:02:46,951 INFO: Microblog startup [in C:\Users\Raynolds\PycharmProjects\Blog\app\__init__.py:84]
2020-01-26 03:02:55,734 INFO: Microblog startup [in C:\Users\Raynolds\PycharmProjects\Blog\app\__init__.py:84]
